config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :employees do
    member do
      get 'bills', to: 'employees#bills'
    end
  end
  resources :bills, only: [:index, :new, :create, :show]
  root 'employees#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :submitted_employee, class_name: 'Employee'

  def self.total_amount
    sum(:amount)
  end
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :employees
  end
  

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  has_many :bills, foreign_key: 'submitted_employee_id', dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def index
    @bills = Bill.all
  end

  def show
    @bill = Bill.find(params[:id])
  end

  def new
    @bill = Bill.new
    @employees = Employee.all
  end

  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      flash[:success] = 'Bill was successfully created.'
      redirect_to bills_path
    else
      @employees = Employee.all
      flash.now[:error] = 'There was an error creating the bill.'
      render :new
    end
  end

  private

  def bill_params
    params.require(:bill).permit(:amount, :bill_type, :submitted_employee_id)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.all
  end

  def show
    @department = Department.find(params[:id])
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    if @department.update(department_params)
      redirect_to departments_path
    else
      render :edit
    end
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy
    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
    @departments = Department.all
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:success] = 'Employee was successfully created.'
      redirect_to employees_path
    else
      @departments = Department.all
      flash.now[:error] = 'There was an error creating the employee.'
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    @departments = Department.all
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      flash[:success] = 'Employee was successfully updated.'
      redirect_to employees_path
    else
      @departments = Department.all
      flash.now[:error] = 'There was an error updating the employee.'
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    flash[:success] = 'Employee was successfully destroyed.'
    redirect_to employees_path
  end

  def bills
    @employee = Employee.find(params[:id])
    @bills = @employee.bills
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :designation, :department_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/bills/_bill.html.erb
<div id="<%= dom_id bill %>">
  <p>
    <strong>Amount:</strong>
    <%= bill.amount %>
  </p>

  <p>
    <strong>Bill type:</strong>
    <%= bill.bill_type %>
  </p>

  <p>
    <strong>Submitted employee:</strong>
    <%= bill.submitted_employee_id %>
  </p>

</div>

app/views/bills/_form.html.erb
<%= form_with(model: @bill, local: true, class: 'needs-validation') do |form| %>
  <% if @bill.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">There were some errors:</h4>
      <ul>
        <% @bill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control', placeholder: 'Enter amount', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :bill_type, class: 'form-label' %>
    <%= form.select :bill_type, options_for_select(['Food', 'Travel', 'Medical', 'Office Supplies'], selected: @bill.bill_type), { prompt: 'Select Bill Type' }, { class: 'form-select', required: true } %>
  </div>

  <div class="mb-3">
    <%= form.label :submitted_employee_id, "Submitted By", class: 'form-label' %>
    <%= form.collection_select :submitted_employee_id, @employees, :id, :full_name, { prompt: 'Select Employee' }, { class: 'form-select', required: true } %>
  </div>

  <div class="d-flex justify-content-left">
    <%= form.submit @bill.new_record? ? 'Create Bill' : 'Update Bill', class: 'btn btn-primary' %>
    <%= link_to 'Back to bills', bills_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render "form", bill: @bill %>

<br>

<div>
  <%= link_to "Show this bill", @bill %> |
  <%= link_to "Back to bills", bills_path %>
</div>

app/views/bills/index.html.erb
<h1 class="mb-4">Submitted Bills</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Type</th>
      <th>Amount</th>
      <th>Submitted By</th>
      <th>Department</th>
      <th>Date of Submission</th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.bill_type %></td>
        <td><%= number_to_currency(bill.amount) %></td>
        <td><%= bill.submitted_employee.full_name %></td>
        <td><%= bill.submitted_employee.department.name if bill.submitted_employee.department %></td>
        <td><%= bill.created_at.strftime("%Y-%m-%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p class="font-weight-bold">Total Amount: <%= number_to_currency(Bill.total_amount) %></p>
<div class="d-flex justify-content-left">
  <%= link_to 'New Bill', new_bill_path, class: 'btn btn-success' %>
  <%= link_to 'Back to Employees', employees_path, class: 'btn btn-secondary' %>
</div>

app/views/bills/new.html.erb
<h1>New Bill</h1>
<div class="form-container">
  <%= render 'form' %>
</div>

app/views/bills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bill %>

<div>
  <%= link_to "Edit this bill", edit_bill_path(@bill) %> |
  <%= link_to "Back to bills", bills_path %>

  <%= button_to "Destroy this bill", @bill, method: :delete %>
</div>

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Name:</strong>
    <%= department.name %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show this department", @department %> |
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departments</h1>

<div id="departments">
  <% @departments.each do |department| %>
    <%= render department %>
    <p>
      <%= link_to "Show this department", department %>
    </p>
  <% end %>
</div>

<%= link_to "New department", new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @department %>

<div>
  <%= link_to "Edit this department", edit_department_path(@department) %> |
  <%= link_to "Back to departments", departments_path %>

  <%= button_to "Destroy this department", @department, method: :delete %>
</div>

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>First name:</strong>
    <%= employee.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= employee.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= employee.email %>
  </p>

  <p>
    <strong>Designation:</strong>
    <%= employee.designation %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= employee.department_id %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: @employee, local: true, class: 'needs-validation') do |form| %>
  <% if @employee.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">There were some errors:</h4>
      <ul>
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, class: 'form-label' %>
    <%= form.text_field :first_name, class: 'form-control', placeholder: 'Enter first name', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, class: 'form-label' %>
    <%= form.text_field :last_name, class: 'form-control', placeholder: 'Enter last name', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control', placeholder: 'Enter email', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :designation, class: 'form-label' %>
    <%= form.text_field :designation, class: 'form-control', placeholder: 'Enter designation', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :department_id, "Department", class: 'form-label' %>
    <%= form.collection_select :department_id, Department.all.uniq, :id, :name, { prompt: 'Select a Department' }, { class: 'form-select', required: true } %>
  </div>

  <div class="d-flex justify-content-left">
    <%= form.submit @employee.new_record? ? 'Create Employee' : 'Update Employee', class: 'btn btn-primary' %>
    <%= link_to 'Back to employees', employees_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/employees/bills.html.erb
<h1 class="mb-4">Bills for <%= @employee.full_name %></h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Type</th>
      <th>Amount</th>
      <th>Date of Submission</th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.bill_type %></td>
        <td><%= number_to_currency(bill.amount) %></td>
        <td><%= bill.created_at.strftime("%Y-%m-%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p class="font-weight-bold">Total Amount: <%= number_to_currency(@bills.sum(:amount)) %></p>
<div class="d-flex justify-center">
  <%= link_to 'New Bill', new_bill_path, class: 'btn btn-success' %>
  <%= link_to 'Back to Employees', employees_path, class: 'btn btn-secondary' %>
</div>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

app/views/employees/index.html.erb
<h1>Employees</h1>
<div class="table-container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Designation</th>
        <th>Department</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.first_name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.email %></td>
          <td><%= employee.designation %></td>
          <td><%= employee.department.name if employee.department %></td>
          <td>
            <div class="inline-buttons">
              <%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-warning' %>
              <%= button_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              <%= link_to 'View Bills', bills_employee_path(employee), class: 'btn btn-info' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'New Employee', new_employee_path, class: 'btn btn-success' %>
<%= link_to 'View All Bills', bills_path, class: 'btn btn-info' %>
<%= link_to 'New Bill', new_bill_path, class: 'btn btn-success' %>

app/views/employees/new.html.erb
<h1>New Employee</h1>
<div class="form-container">
  <%= render 'form' %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <%= value %>
    </div>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReimbursementPortal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>